
<style type="text/css">

	footer
		{
		  background-color: #282828;
		  color: #aba8a8;
		}
		.footer-wigdet
		{
		  /*background-color:#ff9800a1;*/
		  margin: 0 10px;
		  text-align: justify;
		}
		.widget-title
		{
		  color: #fff
		  margin-bottom:40px;
	      margin-top: 20px;
		  text-transform: uppercase;
		  font-size: 17px;
		  letter-spacing: 2.5px;

		}
		.about-widget
		{
			margin-left: 200px;
			margin-right: 30px;
		}
		.about-widget p
		{
		  line-height: 20px;
		  margin: 10px 0 30px 0;
		}

		.cards i
		{
			display:inline-block;
			font-size: 30px;
			margin-right: 12px;
		}

		.about-widget p span
		{
			margin-right: 10px;
		}

		.categories-widget, .information-widget
		{
			margin-left: 50px;
		}
		.contact-widget
		{
			margin-left: 50px;
		}
		.footer-widget ul li
		{
			padding-bottom: 8px;

		}

		.footer-widget ul li a
		{
			color: #aba8a8;
			text-decoration: none;

		}
		.footer-widget ul li a:hover
		{
			color: #d2d2d2;
			margin-left: 10px;
			transition: all .2s ease;

		}
		.contact-address ,.contact-number ,.contact-email
		{
			padding-bottom: 12px;
			border-bottom: 1px solid #9a98988c;
			line-height: 20px; 
			font-weight: normal;
		}
		.contact-number, .contact-email
		{
			margin: 10px 0;
		}
		.contact-address i, .contact-number i, .contact-email i
		{
			margin-right: 10px;
		}

		.social-widget a
		{
			display: inline-block;
			font-size: 28px;
			color: #aba8a8;
			margin-right: 14px;
		}
		.social-widget a:hover
		{
			color: #d2d2d2;
			transition: all .5s ease;
		}

		.copyright
		{
			background-color: #000;
			padding: 10px 10px; 
		}

		.copyright p
		{
			color: #d2d2d2;
			text-align: center;
		}
		.copyright p a
		{
			text-decoration: none;
			color: #d2d2d2;
		}

</style>

<!--  -->
	<div id="about"></div>
	<div class="container-fluid bg-white mt-5 mb-2">
		<div class="row">
			<div class="col">
				<h3>About <b>Us</b></h3>
			</div>
		</div>
		<div class="row">
			<div class="col-1"></div>
			<div class="col-10">
				<p style="margin-top: -25px;"><h9>
					Electronic Commerce is process of doing business through computer networks. A person sitting on his chair in front of a computer can access all the facilities of the Internet to buy or sell the products.
					Unlike traditional commerce that is carried out physically with effort of a person to go & get products,
					ecommerce has made it easier for human to reduce physical work and to save time.
					With respect to the idea of doing business electronically over network. we have developed an E-Commerce
					website that will simply explain how business transaction can be executed across an unreliable and
					unsecured medium like the internet.</h9></p>
				<p><h9>
					In our E-Commerce site we will be providing facilities such as registration into our site, login, customer
					account, checkout, product browsing, order management, cart management, search engine optimization,
					etc. As our E-Commerce site is for Electronic Gadgets, it will contain gadgets such as Mobiles, Laptops,
					Television, Electronic Accessories and Home Appliances. Each gadget type will contain numerous
					products with detail info. We will be providing facility to add the product you wish to buy into the cart
					and also you can order the product. Additional features such as ‘deals of the day’ is also added.
				</h9></p>
			</div>
			<div class="col-1"></div>
		</div>
	</div>

	<!--  --><div id="terms"></div>
	<div class="container-fluid bg-white mb-2">
		<div class="row">
			<div class="col">
				<h3>Terms & <b>Conditions</b></h3>
			</div>
		</div>
		<div class="row">
			<div class="col-1"></div>
			<div class="col-10">
				<p><h9>This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
				This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name [www.flipkart.com][www.flipkart.com] (“Website”), including the related mobile site and mobile application (hereinafter referred to as “Platform”)</h9></p>

				<p><h9>The Platform is owned by Flipkart Internet Private Limited a company incorporated under the Companies Act, 1956 with its registered office at Buildings Alyssa, Begonia & Clover, Embassy Tech Village, Outer Ring Road, Devarabeesanahalli Village, Bengaluru – 560103, Karnataka, India and its branch offices at 2nd Floor, Block F (Flora), Embassy Tech Village, Outer Ring Road, Devarabeesanahalli Village, Bengaluru-560103, Karnataka, India and; 447/C, 12th Main, 4th Block, Koramangala, Bengaluru-560034, Karnataka, India (hereinafter referred to as "Flipkart").	Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with Flipkart Internet Private Limited and these terms and conditions including the policies constitute Your binding obligations, with Flipkart.
				</h9></p>

				<p><h9>For the purpose of these Terms of Use, wherever the context so requires "You" or "User" shall mean any natural or legal person who has agreed to become a buyer on the Platform by providing Registration Data while registering on the Platform as Registered User using the computer systems. Flipkart allows the User to surf the Platform or making purchases without registering on the Platform. The term "We", "Us", "Our" shall mean Flipkart Internet Private Limited.

				When You use any of the services provided by Us through the Platform, including but not limited to, (e.g. Product Reviews, Seller Reviews), You will be subject to the rules, guidelines, policies, terms, and conditions applicable to such service, and they shall be deemed to be incorporated into this Terms of Use and shall be considered as part and parcel of this Terms of Use. We reserve the right, at Our sole discretion, to change, modify, add or remove portions of these Terms of Use, at any time without any prior written notice to You. It is Your responsibility to review these Terms of Use periodically for updates / changes. Your continued use of the Platform following the posting of changes will mean that You accept and agree to the revisions. As long as You comply with these Terms of Use, We grant You a personal, non-exclusive, non-transferable, limited privilege to enter and use the Platform.
				</h9></p>

				<p><h9>ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING. By impliedly or expressly accepting these Terms of Use, You also accept and agree to be bound by Flipkart Policies 	((including but not limited to Privacy Policy available at Privacy) as amended from time to time.</h9></p>
			</div>
			<div class="col-1"></div>
		</div>
	</div>
	<!--  --><div id="returns"></div>
	<div class="container-fluid bg-white mb-2">
		<div class="row">
			<div class="col">
				<h3>Returns & <b>Exchange</b></h3>
			</div>
		</div>
		<div class="row">
			<div class="col-1"></div>
			<div class="col-10">
				<p><h9>All ecommerce based websites that intend to sell online are required to have a stated refund and cancellation policy so that any customer can, if the need arises, return the good purchased. This gives a customer recourse if they change their mind about the purchase made and enables the consumer to claim a refund for the payment made towards such purchase. A policy outlining the guidelines in case a cancellation and/or refund is done on a purchase is essential as it lays down the course of action a customer and the company can take. If a company does not have a stated policy, it would infringe a customer’s right to redressal. 
				</h9></p> 

				<p><h9>Cancellation is the process of making a return of a previously made purchase from an ecommerce website. The purpose of cancellation could vary from customer dissatisfaction with the product to  defective or faulty goods/merchandise purchased. Different ecommerce sites have different cancellation policies that suits the operations of the company. Flipkart and Amazon cancellation policy states that an item cannot be cancelled after delivery of the good. After ordering for the good, and upto the time of delivery, the customer can cancel the order online.

				To refund literally means to pay a customer back who is not satisfied with the goods or services purchased online. A customer may also be entitled for a refund if they have been over charged or over invoiced. After a customer has cancelled/returned good/s, if any payment was made online in lieu for the purchase of such goods, then the payment made earlier has to be refunded back to the customer. The refund policy will state the terms of refund (what will be refunded, such as: store credit, cash refund, exchange of goods, etc.) The timeline for which a refund can be made and claimed is usually stated in the refund policy (Return within 7 days, 30 days, 90 days, etc.). Most countries have regulations within industries for companies to include a refund policy, especially for online stores.</h9></p>

				<p><h9>
					Several websites offer prepared and ready to use templates based on existing policies and standard clauses of most other companies. A refund and cancellation policy should be unique, customizable and beneficial for a website/company. A template may initially guide you, but specialized help from legal professionals are required to draft an appropriate and concrete refund and cancellation policy for your company. Our folks here at LegalDesk.com have been drafting such policies and agreements for individuals and companies alike successfully. Any ecommerce website looking for the best services (whether it be drafting of agreements, documents and/or company policies) in the industry, contact us and we will take care of the rest.
				</h9></p>
			</div>
			<div class="col-1"></div>
		</div>
	</div>

	<!--  --><div id="privacy"></div>
	<div class="container-fluid bg-white">
		<div class="row">
			<div class="col">
				<h3>Privacy <b>Policy</b></h3>
			</div>
		</div>
		<div class="row">
			<div class="col-1"></div>
			<div class="col-10">
				<h5>WHAT PERSONAL INFORMATION WE COLLECT ?</h5><br>
				<p><h9>					

When you visit the Site, we automatically collect certain information about your device, including information about your web browser, IP address, time zone, and some of the cookies that are installed on your device.

Additionally, as you browse the Site, we collect information about the individual web pages or products that you view, what websites or search terms referred you to the Site, and information about how you interact with the Site. We refer to this automatically collected information as Device Information.

We collect Device Information using the following technologies:

    Cookies are data files that are placed on your device or computer and often include an anonymous unique identifier.

    Log files track actions occurring on the Site, and collect data including your IP address, browser type, Internet service provider, referring/exit pages, and date/time stamps.

Mention all other tracking tools and/or technologies being used by your website.

Also, when you make a purchase or attempt to make a purchase through the Site, we collect certain information from you, including your name, billing address, shipping address, payment information (including credit card numbers Mention all types of accepted payments, email address, and phone number. This is called Order Information.

Make sure you mention all other information that you collect.

By Personal Information in this Privacy Policy, we are talking both about Device Information and Order Information.</h9></p>

<br><h5>HOW DO WE USE YOUR PERSONAL INFORMATION</h5><br>
<p class="pb-3"><h9>
We use the Order Information that we collect generally to fulfil any orders placed through the Site (including processing your payment information, arranging for shipping, and providing you with invoices and/or order confirmations).

Additionally, we use this Order Information to: - Communicate with you. - Screen our orders for potential risk or fraud. - When in line with the preferences you have shared with us, provide you with information or advertising relating to our products or services.

We use the Device Information that we collect to help us screen for potential risk and fraud (in particular, your IP address), and more generally to improve and optimize our Site.
				</h9></p>
			</div>
			<div class="col-1"></div>
		</div>
	</div>

<footer>	

	<div class="copyright" style="background: darkgrey; height: 44px;">
		<div class="container-fluid">
			<div class="row">
				<div class="col text-center">
					<h6 class="text-white">
						<a href="#backTop" style="text-decoration: none; color: white;">
							Back to Top</a>
					</h6>
				</div>
			</div>
		</div>
	</div>

    <div class="container-fluid">
        <div class="row">
            <div class="col-4">
                <div class="footer-widget about-widget">
                    <h2 class="widget-title">About</h2>

                    <p class="pt-4" style="letter-spacing: 1.5px; word-spacing: 2px;">E-Mart is a online Shopping Site in India for Mobiles, Laptops, Television, Accessories, Kitchen Appliances etc.</p>

                    <div class="cards">
                        <i class="fab fa-cc-mastercard"></i>
                        <i class="fab fa-cc-visa"></i>
                        <i class="fab fa-cc-paypal"></i>
                        <i class="fab fa-cc-amex"></i>
                        <i class="fab fa-cc-discover"></i>
                    </div>

                    <p><span><i class="fas fa-lock"></i></span>Secure online Payment</p>
               </div>

            </div>
            <div class="col-2 pb-3 mb-4">
                <div class="footer-widget categories-widget ">
                    <h2 class="widget-title mb-4">Categories</h2>

                    <ul>
                      <li><a href="mobile.php">Mobile</a></li>
                      <li><a href="laptop.php">Laptop</a></li>
                      <li><a href="television.php">Television</a></li>
                      <li><a href="accessories.php">Accessories</a></li>
                      <li><a href="kitchen_appliance.php">Kitchen Appliances</a></li>                    
                    </ul>
                </div>
            </div>
   
            <div class="col-2">
                <div class="footer-widget information-widget">
                    <h2 class="widget-title mb-4">Information</h2>
                        <ul>
                          <li><a href="#about">About us</a></li>
                          <li><a href="#terms">Term & Condition</a></li>
                          <li><a href="#returns">Return & Exchange</a></li>
                          <li><a href="#privacy">Privacy Policy</a></li>
                        </ul>
                </div>
            </div>
  
            <div class="col-4 pb-3">
                <div class="footer-widget contact-widget">
                    <h2 class="widget-title mb-4">Contact</h2>

                    <div class="contact-address">
                        <i class="fas fa-map-marker"></i> Address : Sainagar, Amravati, Maharashtra, India. Pin-Code : 444607
                    </div>

                    <div class="contact-number">
                        <i class="fas fa-phone"></i> Phone : +91 83293427**
                    </div>

                    <div class="contact-email">
                        <i class="fas fa-envelope"></i> Email : vermakrishna****@gmail.com
                    </div>

                    <div class="social-widget" style="padding-top: 6px;">
                        <a href="#"><i class="fab fa-facebook-square"></i></i></a>
                        <a href="#"><i class="fab fa-google-plus-square"></i></a>
                        <a href="#"><i class="fab fa-instagram-square"></i></a>
                        <a href="#"><i class="fab fa-youtube-square"></i></a>
                        <a href="#"><i class="fab fa-twitter-square"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>

	<div class="copyright" style="margin-top: -32px; height: 55px;">
	   <div class="container pb-0">
	      <p style="letter-spacing: 2.4px; word-spacing: 3px; height:20px; margin-top: 8px; font-size: 19px;">
	      	Copyright © <script type="text/javascript">document.write(new Date().getfullyear());</script>
	            2021 All rights reserved
	      </p>    
	  </div>
	</div>
</footer>
